# sudo cp deploy/newsyslog-notify.conf /etc/newsyslog.d/notify.conf
# logfilename                               mode count size(KB) when  flags
/usr/local/var/log/notify/*.log              644  14    20480    *     GJ
